server:
  port: 16003

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    # 发送同一类消息的设置为同一个group，保证唯一
    group: rocketmq-group
    # 消息最大长度 默认1024*4(4M)
    maxMessageSize: 4096
    # 发送消息超时时间,默认3000
    sendMessageTimeout: 3600
    # 发送消息失败重试次数，默认2
    retryTimesWhenSendFailed: 2
